### ISSUE TITLE
downloader.py gets into infinite loop, downloads a 404 error page.

### ISSUE THREAD

**Issue by Insidious611** [clementine-player/Dependencies#7]
Trying to follow https://github.com/clementine-player/Clementine/wiki/Compiling-from-Source-(Mac-OS-X) but when I run "make" in /src/macosx, downloader.py just spams my screen with this:

"Downloading boost-1.50.tar.bz2...."
over and over again. Edited it myself to have it print out nb_retries and it's getting up into the hundreds. Checked the downloads folder and the file is just a 1.6kb custom 404 error page. Looks like your URLs need updating? 404 needs handled more gracefully too, imo.

**Comment by Insidious611** [comment]
Looks like it's that http://googledrive.com/host/ urls in general are no longer supported. I opened the folder ID in google drive on a browser and downloaded it as a zip, for now.

**Comment by ArnaudBienner** [comment]
Yes, it seems you're right :(
I found this blogpost from Google saying this functionality is now deprecated: https://gsuiteupdates.googleblog.com/2015/08/deprecating-web-hosting-support-in.html?visit_id=1-636145841092219545-1393120976&hl=en&rd=1
Looks like we'll need to move the files somewhere else.

**Comment by ArnaudBienner** [comment]
@davidsansome @hatstand FYI I moved the dependencies to Google Cloud Platform, since Google Drive URLs are deprecated (see blogpost above). This seems to be the solution suggested by Google to replace Google Drive.

**Comment by hatstand** [comment]
That means we're now paying for the storage and every download.

**Comment by ArnaudBienner** [comment]
Ah, I didn't know that.
That sounds bad :(
@hatstand do know the details of the billing? Is it free for a limited, small usage? Or even a few downloads will cost you something?
If so, I will revert the changes and remove the bucket.
In the meantime, I will try to find another solution, but let me know if you have anything in mind (maybe the same server where website's image are stored?)
